exclude controller:blueprint
This avoids:

2018-10-03T01:07:15,706 | WARN  | main             | Reflections
| could not get type for name
org.osgi.service.blueprint.reflect.ServiceReferenceMetadata from any
class loader
org.reflections.ReflectionsException: could not get type for name
org.osgi.service.blueprint.reflect.ServiceReferenceMetadata
	at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:390)
[org.reflections.reflections-0.9.11.jar:?]
	at org.reflections.Reflections.expandSuperTypes(Reflections.java:381)
[org.reflections.reflections-0.9.11.jar:?]
	at org.reflections.Reflections.<init>(Reflections.java:126)
[org.reflections.reflections-0.9.11.jar:?]
	at org.reflections.Reflections.<init>(Reflections.java:168)
[org.reflections.reflections-0.9.11.jar:?]
	at org.reflections.Reflections.<init>(Reflections.java:141)
[org.reflections.reflections-0.9.11.jar:?]
	at org.opendaylight.infrautils.inject.ClassPathScanner.<init>(ClassPathScanner.java:44)
[ch.vorburger.opendaylight.simple.poc-1.5.0-SNAPSHOT.jar:?]
	at org.opendaylight.genius.simple.GeniusMain.main(GeniusMain.java:18)
[ch.vorburger.opendaylight.simple.poc-1.5.0-SNAPSHOT.jar:?]
Caused by: java.lang.ClassNotFoundException:
org.osgi.service.blueprint.reflect.ServiceReferenceMetadata
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
~[?:1.8.0_181]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_181]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
~[?:1.8.0_181]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_181]
	at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:388)
~[org.reflections.reflections-0.9.11.jar:?]
	... 6 more

and:

2018-10-03T01:07:15,717 | WARN  | main             | Reflections
| could not get type for name
org.osgi.service.blueprint.container.BlueprintListener from any class
loader
org.reflections.ReflectionsException: could not get type for name
org.osgi.service.blueprint.container.BlueprintListener
	at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:390)
[org.reflections.reflections-0.9.11.jar:?]
	at org.reflections.Reflections.expandSuperTypes(Reflections.java:381)
[org.reflections.reflections-0.9.11.jar:?]
	at org.reflections.Reflections.<init>(Reflections.java:126)
[org.reflections.reflections-0.9.11.jar:?]
	at org.reflections.Reflections.<init>(Reflections.java:168)
[org.reflections.reflections-0.9.11.jar:?]
	at org.reflections.Reflections.<init>(Reflections.java:141)
[org.reflections.reflections-0.9.11.jar:?]
	at org.opendaylight.infrautils.inject.ClassPathScanner.<init>(ClassPathScanner.java:44)
[ch.vorburger.opendaylight.simple.poc-1.5.0-SNAPSHOT.jar:?]
	at org.opendaylight.genius.simple.GeniusMain.main(GeniusMain.java:18)
[ch.vorburger.opendaylight.simple.poc-1.5.0-SNAPSHOT.jar:?]
Caused by: java.lang.ClassNotFoundException:
org.osgi.service.blueprint.container.BlueprintListener
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
~[?:1.8.0_181]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_181]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
~[?:1.8.0_181]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_181]
	at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:388)
~[org.reflections.reflections-0.9.11.jar:?]
	... 6 more

and:

2018-10-03T01:07:15,850 | WARN  | main             | Reflections
| could not get type for name
org.apache.aries.blueprint.ext.ComponentFactoryMetadata from any class
loader
org.reflections.ReflectionsException: could not get type for name
org.apache.aries.blueprint.ext.ComponentFactoryMetadata
	at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:390)
[org.reflections.reflections-0.9.11.jar:?]
	at org.reflections.Reflections.expandSuperTypes(Reflections.java:381)
[org.reflections.reflections-0.9.11.jar:?]
	at org.reflections.Reflections.<init>(Reflections.java:126)
[org.reflections.reflections-0.9.11.jar:?]
	at org.reflections.Reflections.<init>(Reflections.java:168)
[org.reflections.reflections-0.9.11.jar:?]
	at org.reflections.Reflections.<init>(Reflections.java:141)
[org.reflections.reflections-0.9.11.jar:?]
	at org.opendaylight.infrautils.inject.ClassPathScanner.<init>(ClassPathScanner.java:44)
[ch.vorburger.opendaylight.simple.poc-1.5.0-SNAPSHOT.jar:?]
	at org.opendaylight.genius.simple.GeniusMain.main(GeniusMain.java:18)
[ch.vorburger.opendaylight.simple.poc-1.5.0-SNAPSHOT.jar:?]
Caused by: java.lang.ClassNotFoundException:
org.apache.aries.blueprint.ext.ComponentFactoryMetadata
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
~[?:1.8.0_181]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_181]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
~[?:1.8.0_181]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_181]
	at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:388)
~[org.reflections.reflections-0.9.11.jar:?]
	... 6 more

Signed-off-by: Michael Vorburger <mike@vorburger.ch>